# Generated by Django 3.1.7 on 2021-03-28 15:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='correct',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='text',
            new_name='user_ans',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='q_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(default='nnn', max_length=400),
        ),
        migrations.AddField(
            model_name='question',
            name='q_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
