# Generated by Django 3.1.7 on 2021-03-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210329_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='user_ans',
            new_name='answer',
        ),
    ]
