# Generated by Django 3.1.7 on 2021-03-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210329_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_ans',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
