# Generated by Django 3.1.7 on 2021-03-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210330_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
