# Generated by Django 3.1.7 on 2021-03-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_question_q_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_id',
        ),
    ]
