# Generated by Django 3.1.7 on 2021-03-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='q_id',
            new_name='question_id',
        ),
    ]
