# Generated by Django 3.1.7 on 2021-03-31 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_question_q_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_id',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
