# Generated by Django 3.1.7 on 2021-03-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210331_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
