# Generated by Django 3.1.7 on 2021-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_answers_q_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
