# Generated by Django 3.1.7 on 2021-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_quiz_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tip',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
