# Generated by Django 3.1.7 on 2021-04-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210401_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='q_id',
            new_name='q',
        ),
    ]
