# Generated by Django 3.1.7 on 2021-04-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_quiz_quiz_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
    ]
