# Generated by Django 3.1.7 on 2021-04-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_auto_20210408_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject', verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
