# Generated by Django 3.1.7 on 2021-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210409_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='flashcards', max_length=30, null=True),
        ),
    ]
